<?php

return [
    'html_lang'                   => 'en',

    'page_title'                  => 'Survey ID Generator',
    'h1'                          => 'Survey ID Generator',

    'whats_this_heading'          => 'What is this?',
    'whats_this_body'             => 'A tool that generates survey-response IDs designed to prevent typos and detect fraudulent answers.',

    'typo_prevention_heading'     => 'Typo prevention',
    'typo_prevention_body'        => 'On portrait-mode smartphones the keys are tightly packed, making adjacent-key typos common. The IDs generated by this tool are designed so that <strong>two keyboard-adjacent characters are never both used at the same character position</strong> across a distributed batch. For example, if some ID has "f" as its third character, no other ID has the keys next to "f" — "d" or "g" — at that position. This lets the form catch typos where the user accidentally pressed an adjacent key.',

    'fraud_detection_heading'     => 'Fraud detection',
    'fraud_detection_body'        => 'IDs from this tool are designed so that random typing cannot pass the form\'s validation. On top of that, of the strings that <em>can</em> pass validation, <strong>only about 1% are actually distributed</strong>. Even if someone reverse-engineers the pattern and submits a plausible-looking string, 99% of the time it is an undistributed (invalid) ID. By cross-checking responses against your list of distributed IDs, you can flag <strong>responses with IDs you never handed out — very likely fraudulent</strong> with high confidence.',

    'usage_heading'               => 'How to use',
    'usage_intro'                 => 'Pressing "Generate" produces an "ID Recognition Pattern" and a "Distribution ID list".',
    'usage_step_pattern'          => 'Set the "ID Recognition Pattern" as the validation on your survey\'s input field. In Google Forms: enable "Response validation" on the question, choose "Regular expression" and "Matches", and paste the pattern into the "Pattern" field.',
    'usage_step_ids'              => 'The "Distribution ID list" is the set of IDs you hand out to respondents. You\'ll need it later to spot fraudulent answers, so save it somewhere — or bookmark this page\'s URL after generating.',

    'generate_heading'            => 'Generate IDs',
    'id_length_label'             => 'ID length (number of valid IDs):',
    'complexity_label_format'     => '%d chars (%s IDs)',
    'generate_button'             => 'Generate',

    'bookmark_url_heading_format' => 'Bookmark URL (valid until %s)',
    'delete_confirm'              => "Server data will be deleted.\nAfter deletion, this URL will no longer work.\nProceed?",
    'delete_button'               => 'Delete server data',
    'pattern_heading'             => 'ID Recognition Pattern (regex for forms)',
    'distribution_heading_format' => 'Distribution IDs (%s)',

    'date_format'                 => 'F j, Y',

    'copyright'                   => '© 2026 Sakilabo Corporation Ltd. All rights reserved.',
];
